mindspore-lab/mindcv

mindcv/scheduler/__init__.py, mindcv/scheduler/multi_step_decay_lr.py, mindcv/scheduler/scheduler_factory.py
=> Add MultiStepDecayLR

mindcv/optim/adamw.py
modify adamw optim to use functional interface
=> modify adamw optim to use functional interface

mindcv/optim/nadam.py, mindcv/optim/optim_factory.py
=> add nadam optimizer

tutorials/deployment.ipynb
Use densenet121 network as an example, show how to deploy a service for model inference.
=> add deployment tutorial

config.py, mindcv/utils/__init__.py, mindcv/utils/callbacks.py, train_and_val.py
=> add train and val

README.md, config.py, mindcv/loss/__init__.py, mindcv/loss/binary_cross_entropy_smooth.py, mindcv/loss/cross_entropy_smooth.py, mindcv/loss/loss_factory.py, tests/modules/test_loss.py
…smoothing and auxilary logits
=> fix & improve loss module: support weighted BCE and CE loss w/ label smoothing, aux logits

mindcv/models/rexnet.py, mindcv/utils/callbacks.py, train.py
fix parallel val while train
fix top k ckpt print
=> fix rexnet

configs/mnasnet/README.md, configs/mnasnet/README_CN.md
=> update mnasnet README

mindcv/version.py, setup.py
=> release 0.0.2-alpha

examples/train_parallel_with_func_example.py
fixed issue  https://github.com/mindspore-lab/mindcv/issues/295
=> fixed example error

configs/convit/README_CN.md
=> Add convit README_CN

README.md, README_CN.md
=> README update

config.py, train.py
=> add dynamic loss scale

config.py, configs/edgenext/edgenext_small_ascend.yaml, mindcv/engine/callbacks.py, mindcv/engine/train_step.py, mindcv/models/model_factory.py, quick_start_CN.md, tests/modules/non_cpu/test_utils.py, tests/tasks/non_cpu/test_train_val_imagenet_subset.py, train.py, tutorials/learn_about_config.md, tutorials/learn_about_config_CN.md, validate.py
Change the name of use_ema and use_clip_grad to ema and clip_grad
=> modify ema name and clip_grad

config.py
Reordering options in config.py for easy understanding~
already in st - `tests/tasks/test_train_val_imagenet_subset.py`
nope
=> [feat] resorting and regrouping options in config.py

config.py, mindcv/optim/lion.py, mindcv/optim/optim_factory.py
=> Add Lion Optimizer

train.py
fix set_seed bug
https://github.com/mindspore-lab/mindcv/pull/406
https://github.com/mindspore-lab/mindcv/pull/407
https://github.com/mindspore-lab/mindcv/pull/408
=> fixed set_seed bug

configs/dpn/README.md, configs/dpn/dpn107_ascend.yaml, configs/dpn/dpn131_ascend.yaml, configs/dpn/dpn92_ascend.yaml, configs/dpn/dpn98_ascend.yaml, mindcv/models/dpn.py
The training recipe and trained weights of DPN are added.
Please refer to "configs/dpn/README.md" for reproducing and testing.
Related Issue: https://github.com/mindspore-lab/mindcv/issues/410
=> [Feature] add training recipe and trained weights of DPN

configs/pvt_v2/README.md, configs/pvt_v2/pvt_v2_b0_ascend.yaml, configs/pvt_v2/pvt_v2_b1_ascend.yaml, mindcv/models/pvtv2.py
The training recipe and trained weights of PVTV2 are added.
Please refer to "configs/pvt_v2/README.md" for reproducing and testing.
Issue:
#423
PR:
#327
=> [Feature] add training recipe and trained weights of PVTV2

configs/mobilenetv3/README.md, mindcv/models/mobilenet_v3.py
update mobilenetv3_small_100 trained weight
None
https://github.com/mindspore-lab/mindcv/pull/74
https://github.com/mindspore-lab/mindcv/pull/250
https://github.com/mindspore-lab/mindcv/pull/277
https://github.com/mindspore-lab/mindcv/pull/367
=> [Feature] update mobilenetv3_small_100 trained weight

configs/vgg/README.md, configs/vgg/vgg11_ascend.yaml, configs/vgg/vgg13_ascend.yaml, configs/vgg/vgg16_ascend.yaml, configs/vgg/vgg19_ascend.yaml, mindcv/models/vgg.py
The training recipe and trained weights of VGG are added.
Please refer to "configs/vgg/README.md" for reproducing and testing.
Related issue: https://github.com/mindspore-lab/mindcv/issues/414
=> [Feature] add training recipe and trained weights of VGG

configs/nasnet/README.md, configs/nasnet/nasnet_a_4x1056_ascend.yaml, mindcv/models/nasnet.py
The training recipe and trained weights of NasNet are added
Please refer to "configs/nasnet/README.md" for reproducing and testing.
Related issue: https://github.com/mindspore-lab/mindcv/issues/438
=> [Feature] add training recipe and trained weights of NasNet

mindcv/models/mobilenet_v2.py
=> delete checkpoint urls from otherwhere (mobilenet v2)

configs/edgenext/README.md, configs/edgenext/edgenext_base_ascend.yaml, configs/edgenext/edgenext_x_small_ascend.yaml, mindcv/models/edgenext.py
[Feature] update edgenext_base and edgenext_x_small
https://github.com/mindspore-lab/mindcv/pull/297
https://github.com/mindspore-lab/mindcv/pull/351
=> [Feature] update edgenext_base and edgenext_x_small

README.md
=> Update README.md to inform arg name change

quick_start.md
=> Fix typo in quick_start.md

configs/bit/README.md, configs/bit/bit_resnet50x3_ascend.yaml, mindcv/models/bit.py
[Feature] add model script, training recipe and trained weights of bit50x3
https://github.com/mindspore-lab/mindcv/pull/446
https://github.com/mindspore-lab/mindcv/pull/273
=> [Feature] add model script, training recipe and trained weights of bit50x3

mindcv/models/__init__.py, mindcv/models/mlpmixer.py
=> add model mlpmixer

configs/crossvit/README.md, configs/crossvit/crossvit_15_ascend.yaml, configs/crossvit/crossvit_18_ascend.yaml, mindcv/models/__init__.py, mindcv/models/crossvit.py
[Feature] add model script, training recipe and trained weights of CrossViT
https://github.com/mindspore-lab/mindcv/issues/418
=> [Feature] add model script, training recipe and trained weights of CrossViT

configs/resnext/README.md, configs/resnext/resnext50_32x4d_ascend.yaml, mindcv/models/resnet.py, tests/modules/test_models.py
The training recipe and trained weights of ResNeXt are added.
Please refer to "configs/resnext/README.md" for reproducing and testing.
#440
=> [Feature] add training recipe and trained weights of ResNeXt

configs/swintransformer/README.md, configs/swintransformer/swin_tiny_ascend.yaml, mindcv/models/swin_transformer.py
The training recipe and trained weights of swin_tiny model are added. 
Please refer to 'config/swintransformer/README.md' for reproducing and testing.
Related issue: https://github.com/mindspore-lab/mindcv/issues/413
=> [Feature] add training recipe and trained weights of Swin Transformer

configs/efficientnet/README.md, configs/efficientnet/efficientnet_b0_ascend.yaml, mindcv/models/efficientnet.py
The training training recipe and trained weights of EfficientNet_b0 is added.
Please refer to "configs/efficientnet/README.md" for reproducing and testing.
close #411
=> [Feature] add training recipe and trained weights of EfficientNet

configs/resnest/README.md, configs/resnest/resnest50_ascend.yaml, mindcv/models/__init__.py, mindcv/models/resnest.py
The model script, training recipe and trained weights of ResNeSt model are added.
Please refer to 'configs/resnest/README.md' for reproducing and testing.
Related issue: closes #422
=> [Feature] add model script, training recipe and trained weights of ResNeSt

configs/pit/README.md, configs/pit/pit_xs_ascend.yaml, mindcv/models/__init__.py, mindcv/models/pit.py
The training recipe and trained weights of PiT are added.
Please refer to "configs/pit/README.md" for reproducing and testing.
Related Issue: close #419
=> [Feature] add model script, training recipe and trained weights of PiT

configs/resnet/resnet_152_gpu.yaml
fixed resnet_152_gpu bug
#540 #541 #542 #543 
=> [fix] fixed resnet_152_gpu bug

configs/googlenet/README.md, configs/googlenet/googlenet_ascend.yaml, mindcv/models/googlenet.py
update model script, training recipe and trained weights of GoogLeNet
Related PR: #397
=> [Feature] update model script, training recipe and trained weights of GoogLeNet

configs/repvgg/README.md, configs/repvgg/repvgg_a1_ascend.yaml, configs/repvgg/repvgg_a2_ascend.yaml, configs/repvgg/repvgg_b0_ascend.yaml, configs/repvgg/repvgg_b1_ascend.yaml, configs/repvgg/repvgg_b2_ascend.yaml, configs/repvgg/repvgg_b3_ascend.yaml, mindcv/models/repvgg.py, tests/modules/test_models.py
The training recipe and trained weights of RepVGG are added.
Please refer to 'configs/repvgg/README.md' for testing and reproducing.
Related issue: https://github.com/mindspore-lab/mindcv/issues/436
=> [Feature] add training recipe and trained weights of RepVGG

configs/sknet/README.md, configs/sknet/skresnet18_ascend.yaml, configs/sknet/skresnet34_ascend.yaml, configs/sknet/skresnext50_32x4d_ascend.yaml, mindcv/models/sknet.py, tests/modules/test_models.py
The training recipe and trained weights of sknet are added.
Please refer to "configs/sknet/README.md" for reproducing and testing.
#437
=> Add training weights and readme file of sknet

configs/vgg/vgg11_ascend.yaml, configs/vgg/vgg13_ascend.yaml, configs/vgg/vgg16_ascend.yaml, configs/vgg/vgg19_ascend.yaml
The unused configuration (smooth factor) of vgg yaml is deleted.
Please refer to 'configs/vgg/README.md' for testing.
Related issue: https://github.com/mindspore-lab/mindcv/issues/414
Related PR: https://github.com/mindspore-lab/mindcv/pull/495
=> Delete unused configuration (smooth factor) of vgg yaml

configs/nasnet/nasnet_a_4x1056_ascend.yaml
The configuration name of dynamic loss scale has been modified to match current configuration file.
Please refer to 'configs/nasnet/README.md' for testing.
Related issue: https://github.com/mindspore-lab/mindcv/issues/438
Related PR: https://github.com/mindspore-lab/mindcv/pull/509, https://github.com/mindspore-lab/mindcv/pull/514
=> Fix training recipe bug of dynamic loss scale in nasnet yaml

configs/convnext/README.md, configs/convnext/convnext_base_ascend.yaml, configs/convnext/convnext_small_ascend.yaml, configs/convnext/convnext_tiny_ascend.yaml, mindcv/models/convnext.py
add training recipe and trained weights of ConvNeXt
Related PR: #18
=> [Feature] add training recipe and trained weights of ConvNeXt

configs/mixnet/README.md, configs/mixnet/mixnet_m_ascend.yaml, mindcv/models/mixnet.py
update training recipe and trained weights of MixNet
Related PR: #467
=> [Feature] update training recipe and trained weights of MixNet

configs/resnet/README.md, mindcv/models/resnet.py
=> [fix] update resnet ckpt url

config.py, configs/bit/bit_resnet101_ascend.yaml, configs/bit/bit_resnet50_ascend.yaml, configs/bit/bit_resnet50x3_ascend.yaml, configs/inception_v3/inception_v3_ascend.yaml, configs/inception_v4/inception_v4_ascend.yaml, configs/mixnet/mixnet_m_ascend.yaml, configs/shufflenet_v1/shufflenet_v1_0.5_ascend.yaml, configs/shufflenet_v1/shufflenet_v1_1.0_ascend.yaml, configs/shufflenet_v1/shufflenet_v1_1.5_ascend.yaml, configs/shufflenet_v1/shufflenet_v1_2.0_ascend.yaml, configs/shufflenet_v2/shufflenet_v2_0.5_ascend.yaml, configs/shufflenet_v2/shufflenet_v2_1.0_ascend.yaml, configs/shufflenet_v2/shufflenet_v2_1.5_ascend.yaml, configs/shufflenet_v2/shufflenet_v2_2.0_ascend.yaml, configs/xception/xception_ascend.yaml, configs/xcit/xcit_tiny_12_p16_ascend.yaml, tests/modules/test_config.py
We need to check if options from yaml config exist in argument parser
see `tests/modules/test_config.py`
=> [feat] check if options from yaml config exist in argument parser

config.py
add description of data sets that can be downloaded
#183 
=> [docs] add description of data sets that can be downloaded

configs/crossvit/README.md
fixed readme url of yaml
#523 
=> [fix] fixed readme url of yaml

README.md, README_CN.md
updated readme what is new for changes to the resnet url
#548 
=> updated readme what is new for changes to the resnet url

configs/regnet/regnet_x_800mf_ascend.yaml
fixed regnet yaml error
issue #559 
=> [Fixed] fixed regnet yaml error

configs/resnext/README.md, configs/resnext/resnext101_32x4d_ascend.yaml, configs/resnext/resnext101_64x4d_ascend.yaml, configs/resnext/resnext152_64x4d_ascend.yaml, mindcv/models/resnet.py
update training recipe and trained weights of ResNeXt
Related PR: #498
=> [Feature] update training recipe and trained weights of ResNeXt

configs/mixnet/README.md
Modify top-1 accuracy of MixNet
Related PR: #467, #570
=> [fix] Modify top-1 accuracy of MixNet

configs/crossvit/README.md, configs/crossvit/crossvit_9_ascend.yaml, mindcv/models/crossvit.py, tests/modules/test_models.py
add crossvit9 ckpt, yaml and ut test
#523 
=> [Feature] add crossvit9 ckpt, yaml and ut test

mindcv/models/vit.py, mindcv/optim/adamw.py, mindcv/optim/adan.py, mindcv/optim/lion.py, mindcv/optim/nadam.py
remove usage of mindspore internal interface _checkparam
test in tests/modules/test_optim.py
=> [fix] remove usage of mindspore internal interface `_checkparam`

configs/mobilevit/README.md, configs/mobilevit/mobilevit_small_ascend.yaml, configs/mobilevit/mobilevit_x_small_ascend.yaml, configs/mobilevit/mobilevit_xx_small_ascend.yaml, mindcv/models/__init__.py, mindcv/models/mobilevit.py
=> [Feature] add model script, training recipe and trained weights of MobileViT

configs/pit/README.md, configs/pit/pit_b_ascend.yaml, configs/pit/pit_s_ascend.yaml, configs/pit/pit_ti_ascend.yaml, mindcv/models/pit.py
update training recipe and trained weights of PiT
Related PR: #492
=> [Feature] update training recipe and trained weights of PiT

mindcv/models/mlpmixer.py
The old version will lead to error:
"RuntimeError: Unknown model mlp_mixer_b_16"
=> fix mlpmixer.py to make it work

configs/coat/README.md, configs/coat/coat_tiny_ascend.yaml, mindcv/models/coat.py
=> coat tiny update

configs/resnest/README.md, configs/resnest/resnest101_ascend.yaml, mindcv/models/resnest.py
update training recipe and trained weights of ResNeSt
Related PR: #532
=> [Feature] update training recipe and trained weights of ResNeSt

mindcv/models/xcit.py
=> [fix] Modify the BatchNorm2d input parameters of xcit model

configs/efficientnet/README.md, configs/efficientnet/efficientnet_b1_ascend.yaml, mindcv/models/efficientnet.py
This PR is proposed for adding training recipe and trained weights of Efficientnet_b1
Please refer to "configs/efficientnet/README.ms" for testing and reproducing.
Related issue: https://github.com/mindspore-lab/mindcv/issues/411
Related PR: https://github.com/mindspore-lab/mindcv/pull/527
=> [Feature] add training recipe and trained weights of Efficientnet_b1

README.md, README_CN.md
=> docs: update `What is New` in `readme`

configs/pvt_v2/README.md, configs/pvt_v2/pvt_v2_b3_ascend.yaml, configs/pvt_v2/pvt_v2_b4_ascend.yaml, mindcv/models/pvtv2.py
update training recipe and trained weights of PVTV2
Related PR: #490
=> [Feature] update training recipe and trained weights of PVTV2

configs/mnasnet/README.md, configs/mnasnet/mnasnet_0.5_ascend.yaml, mindcv/models/mnasnet.py
Add training recipe and pretrained weights of mnasnet_0.5
=> Add training recipe and pretrained weights of mnasnet_0.5

config.py, mindcv/data/auto_augment.py, mindcv/data/transforms_factory.py, tests/modules/test_transforms.py
=> add three data augmentation apis（3-Augment， Augmix，TrivialAugmentWide）

configs/ghostnet/README.md, configs/ghostnet/ghostnet_050_ascend.yaml, configs/ghostnet/ghostnet_100_ascend.yaml, configs/ghostnet/ghostnet_130_ascend.yaml, mindcv/models/ghostnet.py, tests/modules/test_models.py
update model script, add training recipe and trained weights of GhostNet
Related issue: closes #428
=> [Feature] update model script, add training recipe and trained weights of GhostNet

configs/rexnet/README.md
=> fix: update acc@1 of rexnet

configs/vgg/README.md, configs/vgg/vgg11_ascend.yaml, configs/vgg/vgg13_ascend.yaml, configs/vgg/vgg16_ascend.yaml, configs/vgg/vgg19_ascend.yaml, mindcv/models/vgg.py
This PR is proposed to add training recipe and trained weights of vgg (amp level O2).
Please refer to "configs/vgg/README.md" for testing and reproducing.
=> [Feature] add training recipe and trained weights of vgg (amp level O2)

configs/mobilevit/README.md
=> fix: update acc@1 of mobilevit

.github/workflows/docs.yml
=> docs: make sure that only the main branch of the main repo will deploy pages

README.md, README_CN.md, RELEASE.md, mindcv/version.py
=> bump version to 0.2.1

configs/convnextv2/README.md, configs/convnextv2/convnextv2_tiny_ascend.yaml, mindcv/models/convnext.py
Add model script, training recipe and trained weights of ConvNeXt V2
Related issue: #637
=> feat: add model script, training recipe and trained weights of ConvNeXt V2

configs/coat/README.md, configs/coat/coat_mini_ascend.yaml, mindcv/models/coat.py
=> coat_mini update

docs/en/reference/utils.md, docs/zh/reference/utils.md, mindcv/data/dataset_factory.py, mindcv/data/distributed_sampler.py, mindcv/scheduler/scheduler_factory.py, mindcv/utils/__init__.py, mindcv/utils/callbacks.py, mindcv/utils/checkpoint_manager.py, mindcv/utils/logger.py, train.py
=> feat: better logging

mindcv/utils/train_step.py
fix the train_step optimizer.global_step type (int32 -> float32) bug
=> hotfix: fix the train_step optimizer.global_step type (int32 -> float32) bug

README.md, README_CN.md, RELEASE.md, mindcv/version.py
=> bump version to 0.2.2

configs/swintransformerv2/README.md, configs/swintransformerv2/swinv2_tiny_window8_ascend.yaml, mindcv/models/__init__.py, mindcv/models/swin_transformer_v2.py
add model script, training recipe and trained weights of Swin Transformer V2
closes #634
=> feat: add model script, training recipe and trained weights of Swin Transformer V2

config.py, configs/volo/README.md, configs/volo/volo_d1_ascend.yaml, mindcv/models/__init__.py, mindcv/models/volo.py, validate.py
=> [Feature] add model script, training configs and training weights of Volo

config.py, mindcv/data/loader.py, mindcv/data/transforms_factory.py, tests/modules/test_loader.py, tests/modules/test_transforms.py, train.py
support augmentations splits while applying one auto_augmentation
=> supports the augmentations splits

config.py, mindcv/utils/amp.py, mindcv/utils/trainer_factory.py, train.py
=> feat: support custom amp cast list

configs/vit/README.md
Fix typo in configs/vit/readme.md
=> docs: fix typo in configs/vit/readme.md

configs/mixnet/mixnet_m_ascend.yaml, configs/mixnet/mixnet_s_ascend.yaml
=> fix: fix the bug of mixnet config

configs/crossvit/crossvit_15_ascend.yaml, configs/crossvit/crossvit_18_ascend.yaml, configs/crossvit/crossvit_9_ascend.yaml, configs/edgenext/edgenext_base_ascend.yaml, configs/edgenext/edgenext_small_ascend.yaml, configs/edgenext/edgenext_x_small_ascend.yaml, configs/edgenext/edgenext_xx_small_ascend.yaml, mindcv/models/crossvit.py
ema更新后更新crossvit config, 
为加快validate.py推理速度，config文件中增加val_amp_level参数。
修复crossvit的310推理bug.
pr #703 
=> Fix: fix crossvit 310 infer and update yaml

mindcv/models/swintransformerv2.py
fix the incompatibility of swintransformerv2 in ms2.0
closes #700
=> fix: fix the incompatibility of swintransformerv2 on ms2.0

.gitignore, mkdocs.yml, requirements/docs.txt
=> docs: upgrade mkdocs version

mindcv/optim/adamw.py, mindcv/optim/adan.py, mindcv/optim/lion.py, mindcv/optim/nadam.py
=> optimize performance for pynative

mindcv/data/loader.py, mindcv/data/transforms_factory.py
=> add information for the argument “separate” when create transforms

examples/open_clip/difference.py, examples/open_clip/src/open_clip/model.py, examples/open_clip/src/open_clip/openai.py, examples/open_clip/src/open_clip/pretrained.py, examples/open_clip/src/open_clip/transformer.py, examples/open_clip/test.py
=> fix: correct several bugs in open_clip

examples/open_clip/src/open_clip/model.py
fix an bug in open_clip to make it work in difference version of mindspore.
=> fix: fix an bug in open_clip

mindcv/models/hrnet.py, mindcv/optim/adamw.py
This commit upgrades the dependent mindspore to version 2.2 in the branch test/ms2.2.
=> feat: upgrade ms to 2.2

examples/seg/deeplabv3/README.md, examples/seg/deeplabv3/config/deeplabv3plus_s8_dilated_resnet101.yaml, examples/seg/deeplabv3/eval.py
1. fix the typo in eval.py 
2. fix errors in readme.
3. fix the typo in deeplabv3plus yaml file.
=> fix: fix bugs in deeplabv3 examples

README.md, README_CN.md, RELEASE.md, mindcv/version.py
bump version to 0.3.0
N.A.
N.A
=> bump version to 0.3.0

examples/seg/deeplabv3/config/deeplabv3_s16_dilated_resnet101.yaml, examples/seg/deeplabv3/config/deeplabv3_s8_dilated_resnet101.yaml, examples/seg/deeplabv3/config/deeplabv3plus_s16_dilated_resnet101.yaml, examples/seg/deeplabv3/config/deeplabv3plus_s8_dilated_resnet101.yaml, examples/seg/deeplabv3/deeplabv3.py
=> fix deeplabv3

mindcv/models/shufflenetv1.py
Due to MindSpore doesn't support group conv in shufflenet, we need to define the group convolution manually, instead of using the origin `nn.Conv2d` by changing the parameter `group`.
=> fix: Use custom GroupConv instead of nn.Conv2d in shufflenet_v1

configs/pvt/README.md
=> fix pvt loss issue via SATURATION_MODE

mindcv/models/layers/compatibility.py
=> fix: fix the bug of ResizeBilinear for pvt

configs/vit/README.md, configs/vit/vit_b32_224_ascend.yaml, configs/vit/vit_l16_224_ascend.yaml, configs/vit/vit_l32_224_ascend.yaml, mindcv/models/vit.py
- update vit mode code: initialize method, do pre-scale before softmax
- update configuration yaml 
- retrain and update ckpt files
-update vit model code, retrain 3 vit scales,  improve acc;
=> vit_update: initialize method, do pre-scale before softmax, configuration yaml and ckpt files

.github/workflows/publish.yml, configs/pvt/README.md, configs/squeezenet/README.md, configs/squeezenet/squeezenet_1.0_ascend.yaml, configs/vit/README.md, configs/vit/vit_b32_224_ascend.yaml, configs/vit/vit_l16_224_ascend.yaml, configs/vit/vit_l32_224_ascend.yaml, examples/seg/deeplabv3/config/deeplabv3_s16_dilated_resnet101.yaml, examples/seg/deeplabv3/config/deeplabv3_s8_dilated_resnet101.yaml, examples/seg/deeplabv3/config/deeplabv3plus_s16_dilated_resnet101.yaml, examples/seg/deeplabv3/config/deeplabv3plus_s8_dilated_resnet101.yaml, examples/seg/deeplabv3/deeplabv3.py, mindcv/models/layers/compatibility.py, mindcv/models/pvt.py, mindcv/models/shufflenetv1.py, mindcv/models/squeezenet.py, mindcv/models/vit.py
=> update mindcv with MindSpore 2.2.x version 

.github/workflows/publish.yml, configs/pvt/README.md, configs/squeezenet/README.md, configs/squeezenet/squeezenet_1.0_ascend.yaml, configs/vit/README.md, configs/vit/vit_b32_224_ascend.yaml, configs/vit/vit_l16_224_ascend.yaml, configs/vit/vit_l32_224_ascend.yaml, examples/seg/deeplabv3/config/deeplabv3_s16_dilated_resnet101.yaml, examples/seg/deeplabv3/config/deeplabv3_s8_dilated_resnet101.yaml, examples/seg/deeplabv3/config/deeplabv3plus_s16_dilated_resnet101.yaml, examples/seg/deeplabv3/config/deeplabv3plus_s8_dilated_resnet101.yaml, examples/seg/deeplabv3/deeplabv3.py, mindcv/models/layers/compatibility.py, mindcv/models/pvt.py, mindcv/models/shufflenetv1.py, mindcv/models/squeezenet.py, mindcv/models/vit.py
Reverts mindspore-lab/mindcv#770
update to new branch 0.3.1
=> Revert "update mindcv with MindSpore 2.2.x version "

mindcv/models/pvtv2.py
Use `np.linspace` instead of `ops.linspace` since some bugs in `ops.linspace` have not been fixed yet
=> fix: fix the bug of linspace of pvtv2

mindcv/data/mixup.py
latest numpy use np.bool_ instead of np.bool
=> update np.bool to np.bool_

examples/clip/clip/clip.py, examples/det/ssd/train.py, examples/finetune/finetune.py, examples/open_clip/test.py, examples/seg/deeplabv3/train.py, train.py, train_with_func.py, validate.py
=> add jit config level O2 for training scripts to support ms 2.3.0 version

configs/edgenext/edgenext_base_ascend.yaml, configs/edgenext/edgenext_small_ascend.yaml, configs/edgenext/edgenext_x_small_ascend.yaml, configs/edgenext/edgenext_xx_small_ascend.yaml
=> fix edgenext acc

examples/seg/deeplabv3/callbacks.py, examples/seg/deeplabv3/deeplabv3.py, examples/seg/deeplabv3/train.py
=> fix: fix load checkpoint failure for deeplabv3

configs/bit/README.md, configs/cmt/README.md, configs/coat/README.md, configs/convit/README.md, configs/convnext/README.md, configs/convnextv2/README.md, configs/crossvit/README.md, configs/densenet/README.md, configs/dpn/README.md, configs/edgenext/README.md, configs/efficientnet/README.md, configs/ghostnet/README.md, configs/googlenet/README.md, configs/halonet/README.md, configs/hrnet/README.md, configs/inceptionv3/README.md, configs/inceptionv4/README.md, configs/mixnet/README.md, configs/mnasnet/README.md, configs/mobilenetv1/README.md, configs/mobilenetv2/README.md, configs/mobilenetv3/README.md, configs/mobilevit/README.md, configs/nasnet/README.md, configs/pit/README.md, configs/poolformer/README.md
=> chore: renew README forms

README.md
=> docs: add version map between mindspore and mincv

examples/clip/clip/clip.py, examples/det/ssd/train.py, examples/finetune/finetune.py, examples/open_clip/test.py, examples/seg/deeplabv3/train.py, train.py, train_with_func.py, validate.py
=> use GE backend for ms2.3 (#785)

config.py, examples/det/ssd/model.py, examples/seg/deeplabv3/callbacks.py, examples/seg/deeplabv3/deeplabv3.py, examples/seg/deeplabv3/train.py, mindcv/models/vit.py, validate.py
=> merge commits fixing bugs from branch main to branch v0.4.0

configs/pvtv2/pvt_v2_b0_ascend.yaml
=> fix: reset pvtv2_b0 optimizer configs to achieve an acceptable loss result

configs/vit/README.md
- [√] You have read the [Contributing Guidelines on pull requests](https://github.com/mindspore-lab/mindcv/blob/main/CONTRIBUTING.md)
- [√] Your code builds clean without any errors or warnings
- [√] You are using approved terminology
=> Fix perfomance docs
