mindcv/data/loader.py
mindcv/data/mixup.py
mindcv/loss/binary_cross_entropy_smooth.py
train.py

Improve solution #284 of fixing BCE loss w/o mixup.
If we disable mixup or cutmix, then the label is not onehotted. However, `F.binary_cross_entropy_with_logits` only support onehot label which causes problem. The PR above is trying to resolve the bug by add onehot label transform when creating data loader. That's inconsistent when we use CE loss, and coupling loss and data transform together is confusing. The essence of the above problem is that the loss function does not support non-onehot mode, and this PR solves it.
already in ut
#284

improve solution #284 of fixing BCE loss w/o mixup

---

mindcv/data/dataset_download.py
mindcv/data/dataset_factory.py
mindcv/models/utils.py
mindcv/utils/download.py

Set the default download root path as `~/.mindspore`(hereinafter referred to as `${DOWNLOAD_ROOT}`) instead of using the current working directory.
For different types of files, we place them in:
- Checkpoints of pretrained model: `${DOWNLOAD_ROOT}/models`
- Small datasets like mnist cifair10: `${DOWNLOAD_ROOT}/datasets`
We can change the default download path with function `set_default_download_root`, or explicitly pass in the download path when calling function `download_and_extract_archive` or `download_url`.
Already in tests.
None

[feat] add default download root instead of using current working dir

---

config.py
mindcv/engine/__init__.py
mindcv/engine/callbacks.py
mindcv/engine/train_step.py
mindcv/engine/trainer_factory.py
train.py

We abstracted the fragment of the training script about creating a `mindspore.Model` (actually a Trainer) into the function `create_trainer`, a factory method of creating trainers. We believe this abstraction facilitates code readability.
When creating the trainer we need to pass in common components such as networks, optimizer, loss functions etc. as input parameters. Meanwhile, we also need to pass in additional parameters to support Auto Mixed Precision(AMP). Next, we elaborate on the creator's design and principles regarding AMP in details.
1. The level of amp:
We follow the definition from [MindSpore](https://www.mindspore.cn/docs/zh-CN/master/api_python/amp/mindspore.amp.auto_mixed_precis …

[feat] add trainer factory

---

configs/nasnet/nasnet_a_4x1056_ascend.yaml

The typo of model name in nasnet_a_4x1056_ascend.yaml is fixed.
Please refer to the validation part in 'configs/nasnet/README.md' for testing.
Related issue: https://github.com/mindspore-lab/mindcv/issues/438
Related PR: https://github.com/mindspore-lab/mindcv/pull/509

Fix the typo of model name in nasnet_a_4x1056_ascend.yaml

---

tests/modules/test_models.py

- Memory resource is limited on free GitHub action runner. 
- Models with a large number of parameters requires a huge amount of memory for forward calculation.
- Memory is near-incremental during forward computation of multiple consecutive models. MindSpore seems to make Python's GC mechanism fail.
This is just a compromise. The radical solution should be for the PM to provide us with a dedicated self-hosted runners.
Nope

[hotfix] testing model forward on a subset instead of the full collection

---

train.py

We should but cannot set parameter_broadcast=True when invoking `set_auto_parallel_context`, which will cause error on gpu. It's seems to be a weird bug of MindSpore and the reason is still unknown.
inroduced by #487 
fixes #528

[hotfix] disable parameter_broadcast when invoking set_auto_parallel_context

---

configs/resnetv2/README.md
configs/resnetv2/resnetv2_101_ascend.yaml
configs/resnetv2/resnetv2_50_ascend.yaml
mindcv/models/__init__.py
mindcv/models/resnetv2.py

add model script, training configs and training weights of resnetv2
close #442 

[Feature] add model script, training configs and training weights of resnetv2

---

mindcv/models/__init__.py
mindcv/models/cait.py

The model script of cait is added.
Please use 'create_model' part for testing models in cait.
Related issue: https://github.com/mindspore-lab/mindcv/issues/424

[Feature] add model script of cait

---

mindcv/models/vit.py

by default pooling mode is cls in vit, when changed to mean, the dimension will be wrong. fixed in this pr.

Fix vit when pooling mode is not cls.

---

configs/repvgg/README.md
configs/repvgg/repvgg_b1g2_ascend.yaml
configs/repvgg/repvgg_b1g4_ascend.yaml
configs/repvgg/repvgg_b2g4_ascend.yaml
mindcv/models/repvgg.py

This PR is proposed to add training recipe and trained weights of repvgg_b1g2, repvgg_b1g4, repvgg_b2g4.
Please refer to "configs/repvgg/README.md" for testing and reproducing.
Related issue: https://github.com/mindspore-lab/mindcv/issues/436
Related PR: https://github.com/mindspore-lab/mindcv/pull/560, https://github.com/mindspore-lab/mindcv/pull/579

[Feature] add training recipe and trained weights of Repvgg

---

configs/repvgg/README.md

This PR is proposed to correct top-1 and top-5 acc of repvgg_b1g4. The acc is filled with repvgg_b3 acc and has to be fixed.
Please refer to "configs/repvgg/README.md" for reproducing and testing.
Related issue: https://github.com/mindspore-lab/mindcv/issues/436
Related PR: https://github.com/mindspore-lab/mindcv/pull/617

Correct top-1 and top-5 acc of repvgg_b1g4

---

configs/regnet/README.md
configs/regnet/regnet_x_200mf_ascend.yaml
configs/regnet/regnet_x_400mf_ascend.yaml
configs/regnet/regnet_x_600mf_ascend.yaml
configs/regnet/regnet_y_200mf_ascend.yaml
configs/regnet/regnet_y_400mf_ascend.yaml
configs/regnet/regnet_y_600mf_ascend.yaml
configs/regnet/regnet_y_800mf_ascend.yaml
mindcv/models/regnet.py

Add training recipe and pretrained weights of `regnet_x_200mf`, `regnet_x_400mf`, `regnet_x_600mf`, `regnet_y_200mf`, `regnet_y_400mf`, `regnet_y_600mf`, `regnet_y_800mf`.
In fact, the models of these scalings use a unified training recipe. We envisioned training all scalings of `RegNet` using this unified training recipe, but some scalings failed to train. This leaves us with follow-up work.
`regnet_x_800mf` keeps using old recipe for better performance.
No need.
(Is this PR part of a group of changes? Link the other relevant PRs and Issues …

feat: add training recipe & pretrained weights of regnet_(x,y)_(2,4,6,8)00mf

---

config.py
mindcv/utils/__init__.py
mindcv/utils/gradient_accumulation.py
mindcv/utils/train_step.py
mindcv/utils/trainer_factory.py
tests/modules/non_cpu/test_utils.py
train.py

`train.py` supports `accumulate_grad_batches` arguments, which allow the gradient to be accumulated for N steps before performing weight update. So, the model training with a `batch size = N` and `accumulate_grad_batches = 1` is effectively same as a `batch size = N / M` with  `accumulate_grad_batches = M`. Details can be found in [gradient_accumulation](https://www.mindspore.cn/tutorials/experts/en/r1.10/others/gradient_accumulation.html).
The implementation of this PR is based on [mindspore.boost.GradientAccumulation](https://www.mindspore.cn/docs/en/r1.9/_modules/mindspore/boost/grad_accumulation.html#GradientAccumulation) with the following modifications:
1. We have added a overflow check in gradient accumulation. The overflowed gradient at the training step will be skipped.  The …

support gradient accumulation function

---

mindcv/models/efficientnet.py

Correct variable "keep_prob" to "drop_path_prob" and fix the variation trend of drop path rate.
Please refer to "configs/efficientnet" for testing and reproducing.

fix: correct variable "keep_prob" to "drop_path_prob" of efficientnet

---

configs/coat/coat_mini_ascend.yaml
configs/coat/coat_tiny_ascend.yaml
mindcv/utils/checkpoint_manager.py

If using top_k policy, the type checking of `metric` should be `isinstance(metric, Tensor)` instead of `type(metric) is not np.ndarray`.
In `coat.yaml`, `drop_overflow_update: True` should be added when using `loss_scale_type: dynamic`.
#684 
#662 
#600

hotfix: top_k save policy; coat_mini & coat_tiny recipe

---

mindcv/models/helpers.py

The function `load_pretrained` can only delete the parameter `classifier.weight`, but the parameter `opt.classifier.weight` which should be delete together was still kept. This PR fix this bug and delete all parameters in dense layer when load pretrained weights.

fix: fix bug in function load_pretrained

---

.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/publish.yml
requirements/docs.txt

`mindspore` is not compatible with the latest version(10.0.0, relaese on Jul 1, 2023) of `pillow`, which will cause CI [failure](https://github.com/mindspore-lab/mindcv/actions/runs/5452081207/jobs/9919099152).
We force to install version 9.1.1 of pillow.

hoxfix: mindspore is not compatible with the latest version of pillow

---

configs/cmt/README.md
configs/cmt/cmt_small_ascend.yaml
mindcv/models/__init__.py
mindcv/models/cmt.py

The model script, training recipe and pertained weight of cmt_small is added.
Please refer to 'configs/cmt/README.md' for testing and reproducing.

feat: add model script, training recipe and pretrained weight of cmt_s

---

mindcv/loss/__init__.py
mindcv/loss/asymmetric.py
mindcv/loss/jsd.py
mindcv/loss/loss_factory.py
tests/modules/test_loss.py

Jsd loss and asymmetric loss are added.
Related issue: https://github.com/mindspore-lab/mindcv/issues/621

feat: add jsd loss and asymmetric loss

---

configs/README.md

docs: add explanation of suffix 'hardware' of training recipe in config README

---

.github/workflows/publish.yml

When uploading release to pypi, username/password authentication is no longer supported. Migrate to API Tokens instead.

fix(workflow): migrate pypi authentication to api tokens

---

configs/squeezenet/README.md
configs/squeezenet/squeezenet_1.0_ascend.yaml
mindcv/models/squeezenet.py

Squeezenet_1.0在以前的配置下不能稳定训练，偶尔会有validation accuracy 1.0的情况。为了使训练稳定，在训练配置的.yaml文件中增加了warmup_epochs=5。
SqueezeNet_1.0 could not be trained stably under the previous configuration, occasionally resulting in a validation accuracy of 1.0%. To stabilize the training, warmup_epochs=5 was added in the training configuration .yaml file.

fix: add warmup to squeezenet_1.0 config to make the training be stable.

---

mindcv/models/layers/compatibility.py
mindcv/models/pvt.py

1. Use `ops.ResizeBilinearV2` to replace `ops.ResizeBilinear` because MindSpore modified the interface.
2. Use `np.linspace` instead of `ops.linspace` since some bugs in `ops.linspace` have not been fixed yet .

fix: fix bugs of pvt

---

configs/squeezenet/squeezenet_1.0_ascend.yaml

Adjust the amp_level from O2 to O0 to avoid overflow happened during the training of squeezenet_1.0.

fix: fix the config of squeezenet_1.0 with amp_level O0

---

docs/en/how_to_guides/finetune_with_a_custom_dataset.md
docs/zh/how_to_guides/finetune_with_a_custom_dataset.md
examples/finetune/read_images_online.py
examples/finetune/split_files.py

(1)use ***with open()*** rather than ***open()***
(2)use meaningful variables
(3)fix some deep copy problems
修改了以下问题：
1. 参数意义不明确
2. open 之后没有关闭
3. 构造函数缺少传参，images_dir 地址拼写错误
4. 深浅拷贝问题
最后读取后的数据每一个标签都关联上了所有的样本。

fix bugs: fix some bugs in loading data

---

configs/squeezenet/squeezenet_1.0_ascend.yaml

Fix deeplabv3 loss getting nan issue by setting the SATURATION MODE environment variable.
通过设置SATURATION MODE环境变量修复deeplabv3 loss变为nan的问题。

fix deeplabv3 loss issue via SATURATION_MODE

---

configs/squeezenet/squeezenet_1.0_ascend.yaml
examples/det/ssd/data.py

Make ssd data module compatible with mindspore v2.0+ version.
ssd适配mindspore 2.0以后版本的新接口。

Make ssd data module compatible with mindspore v2.0+ version 

---

configs/repvgg/repvgg_a0_ascend.yaml
configs/repvgg/repvgg_a1_ascend.yaml

Change the loss scale type from dynamic to static in repvgg.

fix: fix bugs of repvgg

---

configs/pvt/README.md
configs/pvtv2/README.md
configs/regnet/README.md
configs/repmlp/README.md
configs/repvgg/README.md
configs/res2net/README.md
configs/resnest/README.md
configs/resnet/README.md
configs/resnetv2/README.md
configs/resnext/README.md
configs/rexnet/README.md
configs/senet/README.md
configs/shufflenetv1/README.md
configs/shufflenetv2/README.md
configs/sknet/README.md
configs/squeezenet/README.md
configs/swintransformer/README.md
configs/swintransformerv2/README.md
configs/vgg/README.md
configs/visformer/README.md
configs/vit/README.md
configs/volo/README.md
configs/xception/README.md
configs/xcit/README.md

zht: renew README forms.

---

mindcv/models/vit.py

fix: fix all zero initialized tensor problem for vit

---

config.py
tests/tasks/test_train_val_imagenet_subset.py
validate.py

feat: add device_target config and set default to Ascend.
